import type { Metadata } from "next";
import { Geist, Geist_Mono ,Special_Gothic_Expanded_One} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "@/components/common/Navbar";
import { dark } from '@clerk/themes'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const specialFont = Special_Gothic_Expanded_One({
  variable: "--font-special",
  subsets: ["latin"],
  weight: "400", 
});

export const metadata: Metadata = {
  title: "Orca AI",
  description: "Generated by create next app",
};

// app/layout.tsx

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }} >
      <html lang="en" className="dark" suppressHydrationWarning={true}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${specialFont.variable} antialiased`}
        >
          <Navbar/>
          {/* Add a main tag with top padding to offset the fixed navbar */}
          <main className="pt-16">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}

